---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-ls4-nersc-gaia-dr3-webap
  name: webap
  namespace: ls4-nersc-gaia-dr3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-nersc-gaia-dr3-webap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-nersc-gaia-dr3-webap
    spec:
      containers:
      - image: registry.nersc.gov/m4616/raknop/nersc-desi-gaia-dr3-server
        imagePullPolicy: Always
        name: decat-upload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: desi-gaia-dr3-healpix
          readOnly: true
        # Comment this out to use the code baked into the Dockerfile
        - mountPath: /code
          name: webap-code
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 103988
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - hostPath:
          path: /global/cfs/cdirs/cosmo/data/gaia/dr3/healpix
          type: Directory
        name: desi-gaia-dr3-healpix
      - hostPath:
          path: /global/cfs/cdirs/m4616/desi-gaia-server-rknop-dev
          type: Directory
        name: webap-code
---
apiVersion: v1
kind: Service
metadata:
  name: webap
  namespace: ls4-nersc-gaia-dr3
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-nersc-gaia-dr3-webap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webap-ingress
  namespace: ls4-nersc-gaia-dr3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-nersc-gaia-dr3-webap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webap
  namespace: ls4-nersc-gaia-dr3
spec:
  rules:
  - host: webap.ls4-nersc-gaia-dr3.development.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: webap-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
#   - host: ls4-gaia-dr3-rknop-dev.lbl.gov
#     http:
#       paths:
#       - backend:
#           service:
#             name: webap-ingress
#             port:
#               number: 8080
#         pathType: ImplementationSpecific
#   tls:
#   - hosts:
#     - ls4-gaia-dr3-rknop-dev.lbl.gov
#     secretName: webap-cert
---
