apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-rknop-20260603
  namespace: ls4-nersc-gaia-dr3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-client-vast
  volumeMode: Filesystem
