apiVersion: v1
stringData:
  pghost: postgres
  pgport: "5432"
  pgdbname: gaia_dr3_somecols
  pguser: postgres
  pgpass: PUT THE RIGHT THING HERE
kind: Secret
metadata:
  name: secrets
  namespace: ls4-nersc-gaia-dr3
type: Opaque
